spring:
    application:
        name: blogjson
    Jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/blog
        username: root
        password: root
        drive-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 8081